title: Grzegorz Finke
logo: ./assets/images/profile_img_circle_s.jpg
description: Highly skilled and motivated optomechatronic specialist with over 12 years of experience in both industry and academia. Strong hands-on skills in applied optics supported with 3D/optical desig and programming. Most recently delved into data analysis with SQL, Python, Excel, Tableau.
#show_downloads: true/false
theme: jekyll-theme-minimal
