title: Grzegorz Finke
logo: ./assets/images/profile_img_circle_s.jpg
description: 
  <p style="text-align:justify; font-size:small">Highly skilled and motivated optomechatronic specialist with over 12 years of experience in both industry and academia. Strong hands-on skills in applied optics supported with 3D/optical desig and programming. Most recently delved into data analysis with SQL, Python, Excel, Tableau.</p>
  <a href="https://www.linkedin.com/in/grzegorz-finke-68aa7175/?locale=en_US">LinkedIn Profile<a>

#show_downloads: true/false
theme: jekyll-theme-minimal
