title: Grzegorz Finke
logo: ./assets/images/profile_img_circle_s.jpg
description: 
  <p style="text-align:justify; font-size:smaller line-height:0">Highly skilled and motivated optomechatronic specialist with over 12 years of experience in both industry and academia. Strong hands-on skills in applied optics supported with 3D/optical desig and programming. Most recently delved into data analysis with SQL, Python, Excel, Tableau.</p>
  <a href="https://www.linkedin.com/in/grzegorz-finke-68aa7175/?locale=en_US"><img src="./assets/images/LinkedIn_ico_round_s.png" alt="LinkeIn profile" /></a>
  <a href="https://github.com/Gr3Fin/Python_projects.git"><img src="./assets/images/github_mark_s.png" alt="Github portfolio" /></a>
  <a href="mailto:grzegorz.finke@gmai.com"><img src="./assets/images/gmail_icon_s.png" alt="Gmail address" /></a>

#show_downloads: true/false
theme: jekyll-theme-minimal
